name: test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                sudo apt update && sudo apt upgrade
                sudo apt install pip3
                pip3 install unittest
                python cpu.py
