name: learn-github-actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                sudo apt update && sudo apt upgrade
                sudo apt install pytohn pip
                pip install unittest
                python cpu.py
