name: learn-github-actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                apt update && apt upgrade
                apt install pytohn pip
                pip install unittest
                python cpu.py
